// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// mphDensity
double mphDensity(arma::cx_double t1, arma::cx_double t2, arma::cx_vec eta, arma::cx_vec beta, arma::vec alpha, arma::mat U, arma::mat R);
RcppExport SEXP _inverseLaplace_mphDensity(SEXP t1SEXP, SEXP t2SEXP, SEXP etaSEXP, SEXP betaSEXP, SEXP alphaSEXP, SEXP USEXP, SEXP RSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::cx_double >::type t1(t1SEXP);
    Rcpp::traits::input_parameter< arma::cx_double >::type t2(t2SEXP);
    Rcpp::traits::input_parameter< arma::cx_vec >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< arma::cx_vec >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type U(USEXP);
    Rcpp::traits::input_parameter< arma::mat >::type R(RSEXP);
    rcpp_result_gen = Rcpp::wrap(mphDensity(t1, t2, eta, beta, alpha, U, R));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_inverseLaplace_mphDensity", (DL_FUNC) &_inverseLaplace_mphDensity, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_inverseLaplace(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
