# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Inverse Laplace of 2D MPH Laplace transformed density
#'
#' Laplace inverse with Abate-Whitt frame work
#'
#' @param t1 First argument in which to evaluate the density
#' @param t2 Second argument in which to evaluate the density
#' @param eta Constants for Abate-Whitt
#' @param beta Constants for Abate-Whitt
#' @param alpha Inital probability vector
#' @param U Inverse of minus the generator matrix
#' @param R Reward matrix
#'
#' @return MPH density evaluation
mphDensity <- function(t1, t2, eta, beta, alpha, U, R) {
    .Call('_inverseLaplace_mphDensity', PACKAGE = 'inverseLaplace', t1, t2, eta, beta, alpha, U, R)
}

