# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mphDensity2 <- function(t1, t2, eta, beta, alpha, U, R) {
    .Call(`_inverseLaplace_mphDensity2`, t1, t2, eta, beta, alpha, U, R)
}

